version: '3.7'

services:
  api:
    build:
      context: .
    restart: always
    env_file:
      - .env.development
    ports:
      - 3100:3100
    links:
      - postgres:postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: project_x
      POSTGRES_DATABASE: project_x
    ports:
     - 5432:5432